### ISSUE TITLE
Problem with django 1.9

### ISSUE THREAD

**Issue by MIguelMendo** [mher/chartkick.py#34] opened 2016-03-18 16:42 UTC
__init__() takes exactly 2 arguments (1 given)

**Comment by SalahAdDin** [comment] 2016-03-28 16:30
What's about update this interesting library? @mher

**Comment by freetest** [comment] 2016-05-12 05:24
same +1

**Comment by mher** [comment] 2016-05-12 13:06
please provide the strack trace

**Comment by Thakanian** [comment] 2016-05-16 11:06
init() takes exactly 2 arguments (1 given). 

Can someone provide a solution please.

**Comment by SalahAdDin** [comment] 2016-05-16 12:09
@Thakanian Again, put the full stack trace, not only the last line.

**Comment by Thakanian** [comment] 2016-05-18 09:18
@SalahAdDin 



TypeError at /food/charts/

__init__() takes exactly 2 arguments (1 given)

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/food/charts/
Django Version: 	1.8.6
Exception Type: 	TypeError
Exception Value: 	

__init__() takes exactly 2 arguments (1 given)

Exception Location: 	/home/thakanian/schoolproject/newenv/local/lib/python2.7/site-packages/chartkick/templatetags/chartkick.py in library, line 57
Python Executable: 	/home/thakanian/schoolproject/newenv/bin/python
Python Version: 	2.7.6
Python Path: 	

['/home/thakanian/schoolproject/consumerguide',
 '/home/thakanian/schoolproject/newenv/lib/python2.7',
 '/home/thakanian/schoolproject/newenv/lib/python2.7/plat-i386-linux-gnu',
 '/home/thakanian/schoolproject/newenv/lib/python2.7/lib-tk',
 '/home/thakanian/schoolproject/newenv/lib/python2.7/lib-old',
 '/home/thakanian/schoolproject/newenv/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-i386-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/thakanian/schoolproject/newenv/local/lib/python2.7/site-packages',
 '/home/thakanian/schoolproject/newenv/lib/python2.7/site-packages']

Server time: 	Wed, 18 May 2016 12:16:46 +0300

**Comment by SalahAdDin** [comment] 2016-05-18 16:35
@mher Ok man, the problem is here:
````
if cls._library is None:
            loader = Loader(Engine())
```

These loader is a django loader method, so, i think that was changed with the lastest version, so, you can change the instruction or put a conditionar for older django version.

**Comment by mher** [comment] 2016-06-02 01:41
This bug is fixed in the latest version. Please update to the latest version `pip install -U chartkick`

**Closed by mher** 2016-06-02 01:41 UTC
